# Makefile for CS6240 HW2 project.
# This file just calls the corresponing Makefiles in Project Root with args

# Compiles code and builds jar (with dependencies).
nocombiner-local:
	cd NoCombiner && make alone

nocombiner-cloud:
	cd NoCombiner && make cloud	

# Compiles code and builds jar (with dependencies).
withcombiner-local:
	cd WithCombiner && make alone

withcombiner-cloud:
	cd WithCombiner && make cloud	

# Compiles code and builds jar (with dependencies).
inmappercombiner-local:
	cd InMapperCombiner && make alone

inmappercombiner-cloud:
	cd InMapperCombiner && make cloud	

# Compiles code and builds jar (with dependencies).
secondarysort-local:
	cd SecondarySort && make alone

secondarysort-cloud:
	cd SecondarySort && make cloud	
